pages:
  - 主页: 'index.md'
  - 背景: "Background.md"
#  - 假设: "Assumption.md"
  - 核算: 'caculate.md'
  - 方案:
    - 方案一: "Scheme01.md"
    - 方案二: "Scheme02.md"
    - 方案三: "Scheme03.md"
    - 方案四: "Scheme04.md"
  - 总结: 'Conclusion.md'
    
    

site_name: 'SysEngr_ACEE'
#site_description: 'The Elements of Statistical Learning(ESL) 的中文翻译'

#site_url: https://szcf-weiya.github.io/cn
#repo_url: https://szcf-weiya.github.io/cn

# copyright
copyright: 'Copyright &copy; 2017 SysEngr_ACEE'


extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - js/mymathjax.js

#extra_css:
#  - css/newsprint.css
#  - css/admonition_fix.css

docs_dir: 'docs'

theme_dir: 'material'

extra:
  social:
    - type: 'github'
      link: 'https://github.com/szcf-weiya'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/in/lijun-wang-a11139129/'

google_analytics:
  - 'UA-85007363-5'
  - 'auto'

markdown_extensions:
  - admonition
  - codehilite
  - smarty
  - sane_lists
  - meta
#  - mdx_math

