pages:
  - Home: 'index.md'

site_name: 'ISLRnotes'

#site_description: 'The Elements of Statistical Learning(ESL) 的中文翻译'

site_url: https://szcf-weiya.github.io/cn
repo_url: https://szcf-weiya.github.io/cn

# copyright
copyright: 'Copyright &copy; 2016 weiya'


#extra_javascript:
#  - js/MathJax/MathJax.js?config=TeX-AMS_CHTML
#  - js/mymathjax.js

#extra_css:
#  - css/newsprint.css
#  - css/admonition_fix.css

docs_dir: 'docs'

theme: 'material'

extra:
  social:
    - type: 'github'
      link: 'https://github.com/szcf-weiya'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/in/lijun-wang-a11139129/'

google_analytics:
  - 'UA-85007363-5'
  - 'auto'

markdown_extensions:
  - admonition
  - codehilite
  - smarty
  - sane_lists
  - meta
  - mdx_math

